import {
  AppSettings,
  InstallSettings,
  MediaItem,
  Review,
  ReleaseNote,
  DeveloperSettings,
  PrivacySettings,
  AnalyticsEvent,
  GeneratedApp,
} from '../types';

export const initialAppSettings: AppSettings = {
  id: '00000000-0000-0000-0000-000000000001',
  app_name: '1Xbetfair',
  developer_name: '1Xbetfair Official Limited',
  short_description: 'Live Sports, Exchange Betting, Casino & Instant Multipliers.',
  description: `Experience the official 1Xbetfair application with instant live sports odds, exchange markets, and fast withdrawals.

Built with an ultra-responsive interface, 1Xbetfair gives you real-time access to live match feeds, higher multipliers, instant verification, and 24/7 dedicated customer assistance.

Key Features & Highlights:
• Instant App Launch: Optimized cold-starts with zero stutter or lag.
• Live Sports & Exchange: Real-time dynamic odds and high-speed in-play updates.
• Secure Fast Withdrawals: Quick, verified payouts directly to your account.
• Bank-Grade Data Privacy: Encrypted SSL data channels with high-grade security.
• Universal Compatibility: Smoothly runs as standalone PWA on Android, iOS Safari, and Desktop.
• Regular Updates: Continuously updated for stability, security, and peak performance.`,
  features: [
    'Real-time live sports odds and exchange markets',
    'Instant, secure withdrawal verification',
    'Bank-grade SSL data encryption and privacy',
    'Fluid PWA standalone performance across all devices',
    '24/7 live dedicated customer support',
  ],
  category: 'Sports & Entertainment',
  rating: 4.9,
  review_count: '18.4K reviews',
  download_count: '500K+ downloads',
  age_rating: '18+',
  version: '3.1.0',
  last_updated: 'Today',
  icon_url: '/1xbetfair-icon.png',
  banner_url: '/1xbetfair-icon.png',
  verified: true,
  editors_choice: true,
  site_name: '1Xbetfair',
  site_logo_url: '/1xbetfair-icon.png',
  site_badge_text: 'Verified 1X',
  show_site_badge: true,
  pwa_name: '1Xbetfair App',
  pwa_short_name: '1Xbetfair',
  pwa_theme_color: '#0088cc',
  pwa_background_color: '#000000',
  icon_192_url: '/icon-192.png',
  icon_512_url: '/icon-512.png',
  apple_touch_icon_url: '/apple-touch-icon.png',
  favicon_url: '/favicon.png',
};

export const initialInstallSettings: InstallSettings = {
  id: '00000000-0000-0000-0000-000000000002',
  mode: 'PWA',
  apk_url: '',
  apk_filename: '1xbetfair-release.apk',
  apk_size_bytes: 28400000,
  external_url: 'https://1xbetfair.me',
  ios_store_url: '',
  ios_button_text: 'GET',
  store_theme_mode: 'auto',
  open_new_tab: true,
  confirmation_enabled: false,
  button_text: 'Install',
  initializing_text: 'Initializing...',
  downloading_text: 'Downloading...',
  installing_text: 'Installing...',
  open_text: 'Open',
  success_message: 'Installation initiated for 1Xbetfair.',
  android_message: 'Install 1Xbetfair directly on your Android mobile home screen.',
  ios_message: 'Add 1Xbetfair directly to your iPhone/iPad Home Screen for full screen performance.',
  desktop_message: 'Install 1Xbetfair as a standalone desktop app on your PC or Mac.',
};

export const initialMediaItems: MediaItem[] = [
  {
    id: 'media-1',
    type: 'screenshot',
    url: 'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=720&auto=format&fit=crop&q=80',
    title: 'Fast & Fluid Navigation',
    caption: 'Clean, minimalist UI engineered for high refresh-rate mobile screens.',
    sort_order: 1,
    enabled: true,
  },
  {
    id: 'media-2',
    type: 'screenshot',
    url: 'https://images.unsplash.com/photo-1526470608268-f674ce90ebd4?w=720&auto=format&fit=crop&q=80',
    title: 'Cross-Device Cloud Sync',
    caption: 'Keep your preferences, saved items, and settings unified everywhere.',
    sort_order: 2,
    enabled: true,
  },
  {
    id: 'media-3',
    type: 'screenshot',
    url: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=720&auto=format&fit=crop&q=80',
    title: 'Immersive Entertainment',
    caption: 'High-definition media playback with low-latency responsiveness.',
    sort_order: 3,
    enabled: true,
  },
  {
    id: 'media-4',
    type: 'screenshot',
    url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=720&auto=format&fit=crop&q=80',
    title: 'Privacy & Security First',
    caption: 'Zero third-party trackers and strict transparent data disclosure.',
    sort_order: 4,
    enabled: true,
  },
];

export const initialReviews: Review[] = [
  {
    id: 'rev-1',
    reviewer_name: 'Maram K.',
    rating: 5,
    review_text: 'The best app in its category. Fluid animations, instant loading, and very clean design without annoying banners. Everything works as advertised!',
    review_date: '12 September 2026',
    helpful_count: 87,
    developer_response: 'Good day Maram! Thank you for your wonderful review. Our team continuously tests to ensure peak 60fps performance on all devices!',
    developer_response_date: '12 September 2026',
    published: true,
    featured: true,
    sort_order: 1,
  },
  {
    id: 'rev-2',
    reviewer_name: 'Neha S.',
    rating: 4,
    review_text: 'Solid app with incredible reliability. The dark mode looks gorgeous on my OLED display. Are there any upcoming widget options for the home screen?',
    review_date: '12 September 2026',
    helpful_count: 30,
    developer_response: 'Good day Neha! Yes, our engineering team has included customizable home screen widgets in the upcoming v2.5 release scheduled for next month!',
    developer_response_date: '11 September 2026',
    published: true,
    featured: true,
    sort_order: 2,
  },
  {
    id: 'rev-3',
    reviewer_name: 'DesiMumbaikar',
    rating: 5,
    review_text: 'Super fast setup. Did not require unnecessary permissions or lengthy signup forms. The APK downloaded and installed without a hitch.',
    review_date: '11 September 2026',
    helpful_count: 54,
    developer_response: 'Thank you for highlighting our privacy-first setup!',
    developer_response_date: '11 September 2026',
    published: true,
    featured: false,
    sort_order: 3,
  },
  {
    id: 'rev-4',
    reviewer_name: 'cool_ankit_123',
    rating: 5,
    review_text: "It's okay and works as expected. Very fast on mobile data.",
    review_date: '25 August 2026',
    helpful_count: 12,
    developer_response: undefined,
    developer_response_date: undefined,
    published: true,
    featured: false,
    sort_order: 4,
  },
  {
    id: 'rev-5',
    reviewer_name: 'VikramSingh',
    rating: 5,
    review_text: "I've started enjoying the utility and smooth media navigation again. Clean transitions and solid stability over long sessions.",
    review_date: '25 August 2026',
    helpful_count: 51,
    developer_response: undefined,
    developer_response_date: undefined,
    published: true,
    featured: false,
    sort_order: 5,
  },
];

export const initialReleaseNotes: ReleaseNote[] = [
  {
    id: 'rel-1',
    version: '2.4.1',
    title: 'Performance Enhancements & Display Tuning',
    content: `• Boosted cold-start launch speed by 35% on mobile devices
• Refined gesture sensitivity for edge-swipe navigation
• Optimized offline cache eviction to save user storage
• Minor UI polish on high-DPI desktop viewports`,
    release_date: '10 September 2026',
    published: true,
  },
  {
    id: 'rel-2',
    version: '2.4.0',
    title: 'Major Feature Update & PWA 2.0',
    content: `• Added standalone PWA support with offline caching
• New high-contrast dark theme mode
• Upgraded data protection and TLS 1.3 encryption
• Streamlined install flow and quick launcher`,
    release_date: '15 August 2026',
    published: true,
  },
];

export const initialDeveloperSettings: DeveloperSettings = {
  id: '00000000-0000-0000-0000-000000000003',
  developer_name: 'NexusPlay Global Limited',
  company_name: 'NexusPlay Studios Inc.',
  email: 'support@nexusplayapp.com',
  website: 'https://nexusplayapp.com',
  support_url: 'https://nexusplayapp.com/support',
  address: '100 Silicon Valley Way, Suite 400, San Jose, CA 95110',
  social_links: {
    twitter: 'https://twitter.com/nexusplay',
    discord: 'https://discord.gg/nexusplay',
    telegram: 'https://t.me/nexusplay',
  },
};

export const initialPrivacySettings: PrivacySettings = {
  id: '00000000-0000-0000-0000-000000000004',
  data_collected: [
    'Crash diagnostics and performance logs to optimize responsiveness',
    'Optional basic device specifications (OS version and display resolution)',
  ],
  data_shared: [
    'No data shared with unverified third parties',
    'No personal contact information, phone numbers, or SMS logs collected',
  ],
  encryption: true,
  account_deletion: true,
  privacy_policy_url: '/privacy',
  safety_notes: 'Safety starts with understanding how developers collect and share your data. Data privacy and security practices may vary based on your use, region, and age. The developer provided this information and may update it over time.',
  enabled: true,
};

export const initialAnalyticsEvents: AnalyticsEvent[] = [
  {
    id: 'evt-1',
    event_type: 'install_button_click',
    device_type: 'android',
    browser: 'Chrome Mobile',
    country: 'IN',
    created_at: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: 'evt-2',
    event_type: 'apk_download_click',
    device_type: 'android',
    browser: 'Chrome Mobile',
    country: 'IN',
    created_at: new Date(Date.now() - 3600000 * 4).toISOString(),
  },
  {
    id: 'evt-3',
    event_type: 'install_button_click',
    device_type: 'ios',
    browser: 'Safari Mobile',
    country: 'US',
    created_at: new Date(Date.now() - 3600000 * 8).toISOString(),
  },
  {
    id: 'evt-4',
    event_type: 'external_redirect',
    device_type: 'desktop',
    browser: 'Chrome',
    country: 'GB',
    created_at: new Date(Date.now() - 3600000 * 12).toISOString(),
  },
  {
    id: 'evt-5',
    event_type: 'pwa_install_prompt',
    device_type: 'desktop',
    browser: 'Edge',
    country: 'DE',
    created_at: new Date(Date.now() - 3600000 * 24).toISOString(),
  },
];

export const initialGeneratedApps: GeneratedApp[] = [
  {
    id: '00000000-0000-0000-0000-000000000100',
    app_id: '1xbetfair',
    app_name: '1Xbetfair',
    short_name: '1Xbetfair',
    target_url: 'https://1xbetfair.me',
    icon_url: '/1xbetfair-icon.png',
    icon_192_url: '/icon-192.png',
    icon_512_url: '/icon-512.png',
    apple_touch_icon_url: '/apple-touch-icon.png',
    favicon_url: '/favicon.png',
    theme_color: '#0088cc',
    background_color: '#000000',
    category: 'Sports & Entertainment',
    rating: 4.9,
    review_count: '18.4K reviews',
    download_count: '500K+ downloads',
    version: '3.1.0',
    short_description: 'Official 1Xbetfair - Sports, Live Exchange, Slots & Instant Verification.',
    description: '1Xbetfair delivers premier live sports betting, exchange markets, top multiplier games, and instant withdrawals. Enjoy fast, secure mobile gaming on any device.',
    display_mode: 'standalone',
    embed_mode: 'iframe_seamless',
    button_text: 'Install',
    ios_button_text: 'GET',
    ios_url: '',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '00000000-0000-0000-0000-000000000101',
    app_id: 'crore-bet',
    app_name: 'Crore Bet',
    short_name: 'Crore Bet',
    target_url: 'https://crore-games.com/?__hbus=10',
    icon_url: '/icon-512.png',
    icon_192_url: '/icon-192.png',
    icon_512_url: '/icon-512.png',
    apple_touch_icon_url: '/apple-touch-icon.png',
    favicon_url: '/favicon.png',
    theme_color: '#01875f',
    background_color: '#000000',
    category: 'Casino & Entertainment',
    rating: 4.7,
    review_count: '8.3L reviews',
    download_count: '10L+ downloads',
    version: '1.4.0',
    short_description: 'Slots, live games, higher multipliers and instant verification.',
    description: 'Crore Bet delivers top slots, live games, and instant withdrawal verification. Enjoy seamless mobile gaming.',
    display_mode: 'standalone',
    embed_mode: 'iframe_seamless',
    button_text: 'Install',
    ios_button_text: 'GET',
    ios_url: 'https://crore-games.com/?__hbus=10',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '00000000-0000-0000-0000-000000000102',
    app_id: 'superplay',
    app_name: 'SuperPlay App',
    short_name: 'SuperPlay',
    target_url: 'https://example.com',
    apk_url: 'https://github.com/nexusplay/downloads/releases/download/v2.4.1/nexusplay-pro-v2.4.1.apk',
    apk_filename: 'superplay-pro-v2.4.1.apk',
    icon_url: '/icon-512.png',
    icon_192_url: '/icon-192.png',
    icon_512_url: '/icon-512.png',
    apple_touch_icon_url: '/apple-touch-icon.png',
    favicon_url: '/favicon.png',
    theme_color: '#01875f',
    background_color: '#ffffff',
    category: 'Entertainment & Utilities',
    rating: 4.8,
    review_count: '12K reviews',
    download_count: '500K+ downloads',
    version: '2.4.1',
    short_description: 'Fluid performance, customizable themes, and offline actions.',
    description: 'SuperPlay App is your modern entertainment and utility companion.',
    display_mode: 'standalone',
    embed_mode: 'iframe_seamless',
    button_text: 'Install',
    ios_button_text: 'GET',
    ios_url: 'https://apps.apple.com/app/id1234567890',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
